# Generated by Django 4.2.5 on 2024-04-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(default='', max_length=100, verbose_name='商品名')),
                ('price', models.IntegerField(default=0, verbose_name='値段')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新日')),
            ],
        ),
    ]
